# Generated by Django 2.2.6 on 2019-10-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='adhar',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
