# Generated by Django 2.2.6 on 2019-10-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('share_id', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=30)),
                ('face_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
