# Generated by Django 2.2.6 on 2019-10-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='current_value',
            new_name='sell_value',
        ),
    ]
